### ISSUE TITLE
Import error in Python 3.4

### ISSUE THREAD

**Issue by fitoprincipe** [gee-community/gee_tools#31]
It works fine in python 3.5, but in python 3.4 when doing `from geetools import ui` it throws an error:

> ImportError                               Traceback (most recent call last)
> <ipython-input-9-c21800ff76e7> in <module>()
> ----> 1 from geetools.ui import ipymap
> 
> ~/Projects/eds_vietnam/env/eds_vietnam/lib/python3.4/site-packages/geetools/ui/__init__.py in <module>()
>       4 import threading
>       5 import pprint
> ----> 6 from . import chart, imagestrip, ipymap, ipytools, maptool, dispatcher
>       7 
>       8 from IPython.display import display
> 
> ~/Projects/eds_vietnam/env/eds_vietnam/lib/python3.4/site-packages/geetools/ui/ipymap.py in <module>()
>      14 from .maptool import inverseCoordinates, getImageTile, getGeojsonTile, \
>      15                      getBounds, getZoom, featurePropertiesOutput
> ---> 16 from . import maptool, ipytools
>      17 import threading
>      18 from copy import copy
> 
> ~/Projects/eds_vietnam/env/eds_vietnam/lib/python3.4/site-packages/geetools/ui/ipytools.py in <module>()
>       7 
>       8 from .. import batch
> ----> 9 from .dispatcher import widgetDispatcher
>      10 
>      11 # imports for async widgets
> 
> ~/Projects/eds_vietnam/env/eds_vietnam/lib/python3.4/site-packages/geetools/ui/dispatcher.py in <module>()
>       3 import ee
>       4 from ipywidgets import *
> ----> 5 from . import ipytools
>       6 
>       7 def belongToEE(eeobject):
> 
> ImportError: cannot import name 'ipytools'
